name: iOS Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        # Menambahkan working-directory agar masuk ke folder nutrivision
        run: flutter pub get
        working-directory: nutrivision

      - name: Build iOS (No Codesign)
        # Menambahkan working-directory agar masuk ke folder nutrivision
        run: flutter build ios --release --no-codesign
        working-directory: nutrivision

      - name: Create Payload and IPA
        # Menyesuaikan path folder hasil build
        run: |
          cd nutrivision/build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r NutriVision-iOS.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NutriVision-iOS-Release
          path: nutrivision/build/ios/iphoneos/NutriVision-iOS.ipa
          retention-days: 7
